### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BETTYBETS**

### CODE REVIEW

**Comment by BETTYBETS** [comment]
👌👌

**Comment by BETTYBETS** [comment]
,🙂💯

**Comment by BETTYBETS** [comment]
Updated memvership

**Comment by BETTYBETS** [comment]
Updated membership
🙂👌

**Comment by DSCUBa2020** [comment]
@BETTYBETS you are to update the member.json file not the readme.md fille

**Comment by BETTYBETS** [comment]
SORRY JUST SEEING THIS TODAY

**Pull request closed without merging**
